# -*- coding: utf-8 -*-
"""Clase_5 - Lautaro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mH3MVXoUYENJkswk3DLx6st9BDkn7MaZ

La idea es que ustedes vayan resolviendo los ejercicios sin la necesidad de instalarse nada en sus computadoras. 
Antes que nada, creen una copia de este archivo en su ***Google Drive*** para tener permisos de edición, luego pueden compartirlo con quien quieran, tengan cuidado con los permisos al momento de compartir!!!!!!!. Si quieren, nos pueden compartir su documento a los docentes para que hagamos las correcciones y ayudemos con las dudas.

### Agustin: **agustin.otero@estudiantes.unahur.edu.ar** ###


En los bloques de código como el que les aparece aca abajo, se puede programar en Python, al pararse dentro del bloque, aparecerá un ícono de "*play*" en la esquina superior izquierda, "*clickeando*" en este ícono, se ejecuta el código escrito y se muestra la salida debajo, probemos:

Los operadores logicos funcional tal cual uno lo pensaria gramaticalmente.
Gracias al IDE se pueden poner operaciones logicas y ejecutar el codigo, y el IDE mostrara el resultado.

Probemos:
"""

True and True

True and False

True or False

not True

"""Al igual que los operadores, las comparaciones tambien se pueden hacer sueltas en un cuadro de codigo y verificar los valores obtenidos."""

7>3

7>7

7>=7

"casa" == "Casa"

a = int(input(""))
b = int(input(""))

if b != 0:
  print(a/b)

print("Terminó")

tengoHelado = True

if tengoHelado:
  print("Me como el helado")
else:
  print("No me como el helado")

print("Terminó")

tengoHelado = False
tengoPlata = 500
precioHelado = 650

if tengoHelado:
  print("Como helado")
elif tengoPlata >= precioHelado:
  print("Compro helado")
else:
  print("No hago nada")

print("Terminó")

#Creo una variable
num = 10

while num > 0:
  # modifico la variable para que vaya decreciendo
  num = num - 1
  print(num)

"""Aca tenemos unos ejemplos de aplicaciones de la estructura while, pero estan incompletos.

Leamos y conprendamos el codigo , y llenemos lo que falta para que funcionen correctamente.

Bucle **while** controlado por Conteo
"""

contar=0

while contar < 10:
    print(contar)
    contar = contar + 1

"""Bucle **while** controlado por Evento."""

total = 0

print ("Introduzca un valor a sumar (-1 para salir): ")
valor = int(input())
while valor > -1:
    total = total + valor
    print ("Introduzca el valor  (-1 para salir): ")
    valor = int(input())
print (f"La suma de los valores ingresados es: {total}")

"""### **Ejercicio 1 if**

Escribir un programa pida al usuario dos números enteros e informe por pantalla cual es menor de los dos, si son iguales, indicarlo por separado.
"""

# Ingreso el primer número
num1 = int(input("Ingrese un numero entero "))
# Ingreso el segundo número
num2 = int(input("Ingrese un numero entero "))

# Comparo si el primer numero es más chico que el segundo número
if num1 < num2:
  print(f"{num1} es más chico que {num2}")
# Comparo si el segundo numero es más chico que el primer número
elif num2 < num1:
  print(f"{num2} es mas chico que {num1}")
# Si ninguna comparación es correcta ( si son iguales)
else:
  print(f"Los números ingresados son iguales")

"""### **Ejercicio 2 if**

Escriba un programa que pida tres números y que escriba si son los tres iguales, si hay dos iguales o si son los tres distintos.
"""

#Ingreso el primer número
num1 = int(input("Ingrese un numero entero "))
#Ingreso el segundo número
num2 = int(input("Ingrese un numero entero "))
#Ingreso el tercer número
num3 = int(input("Ingrese un numero entero "))

# Ingreso el operador AND para comparar dos condiciones
if num1 == num2 and num2 == num3:
  print("Los numeros ingresados son iguales")
# Ingreso el operador OR para comprar las tres condiciones 
elif num1 == num2 or num2 == num3 or num3 == num1:
  print("Solo hay dos numeros iguales")
else:
  print("Los numeros son distintos")

"""### **Ejercicio 3 if**

Escriba un programa que pida el año actual y un año cualquiera y que escriba cuántos años han pasado desde ese año o cuántos años faltan para llegar a ese año.
"""

# Pido los datos a comprar
anioActual = int(input("Escriba el año actual "))
anioCualquiera = int(input("Escriba otro año "))
# primero comparo si el año actual es mayor al año cualquier
if anioActual > anioCualquiera:
  anioTotal = anioActual - anioCualquiera
  print(f"Pasaron {anioTotal} desde {anioCualquiera} al {anioActual}")
elif anioActual < anioCualquiera:
  anioTotal = anioCualquiera - anioActual
  print(f"Faltan {anioTotal} para llegar al {anioCualquiera}")
else:
  print("Son los mismos años")

"""### **Ejercicio 4 if**

Escriba un programa que pida dos números enteros y que calcule su división, escribiendo si la división es exacta o no.

Parte 2: 

Mejore el programa anterior haciendo que tenga en cuenta que no se puede dividir por cero:
"""

# Ingreso el primer número
num1 = int(input("Ingrese el dividendo "))
# Ingreso el segundo número
num2 = int(input("Ingrese el divisor "))

# Si el divisor es distinto cero, se puede dividir
if num2 != 0:
  # agrego un operador de resto para saber si es exacta
  if num1 % num2 == 0:
    print("La división es exacta")
  # Caso contrario, no es exacta
  else:
    print("La división NO es exacta")
# Si el divisor es cero entra al bloque else y no hace la división
else:
  print("No se puede dividir por cero")

"""### **Ejercicio 5 if**

Escribir un programa que pida al usuario un número entero del 1 al 7 y muestre por pantalla el día de la semana correspondiente. Controlar que el número se encuentre en el rango correcto, si no es así, informar un error. Por ejemplo, si el número es 2 el día es martes.
"""

# Ingreso el primer número
num1 = int(input("Ingrese un numero entero del 1 al 7 "))

# controlo si el numero ingresado es menor a 1 o mayor a 7
if num1 > 0 and num1 < 7:
  if num1 == 1:
    print("El día es Lunes")
  elif num1 == 2:
    print("El día es Martes")
  elif num1 == 3:
    print("El día es Miércoles")
  elif num1 == 4:
    print("El día es Jueves")
  elif num1 == 5:
    print("El día es Viernes")
  elif num1 == 6:
    print("El día es Sábado")
  else:
    print("Hoy es Domingo")
# Muestro en pantalla que el número ingresado no es válido
else:
  print("El numero ingresado no es válido para un día de semana")

"""### **Ejercicio 6 if**

Las y los alumnas y alumnos de un curso se han dividido en dos grupos A y B de acuerdo al género y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su inicial y género, y muestre por pantalla el grupo que le corresponde.
"""

# Ingreso género
genero = input("Ingrese género másculino con M \no género femenino con F ").upper()
# Ingreso inicial del nombre
inicial = input("Ingrese la inicial de su nombre ").upper()

# Creado dos listas de iniciales
inicialesAHaciaM = ["A","B","C","D","E","F","G","H","I","J","K","L","M"]
inicialesNHaciaZ = ["N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]

# Si el género es femenino
if genero == "F":
  # Si la inicial está dentro de la lista inicialesAHaciaM, grupo A
  if inicial in inicialesAHaciaM:
    print("Es del grupo A")
  # Si no, está en el grupo B
  else:
    print("Es del grupo B")
# Si el género es masculino
elif genero == "M":
  # Si la inicial está dentro de la lista inicialesNHaciaZ, grupo A
  if inicial in inicialesNHaciaZ:
    print("Es del grupo A")
  # Si no, está en el grupo B
  else:
    print("Es del grupo B")

"""### **Ejercicio 7 if**

Escribir un programa para una empresa que tiene salas de juegos para todas las edades y quiere calcular de forma automática el precio que debe cobrar a sus clientes por entrar. El programa debe preguntar al usuario la edad del cliente y mostrar el precio de la entrada. Si el cliente es menor de 4 años puede entrar gratis, si tiene entre 4 y 18 años debe pagar 5 pesos y si es mayor de 18 años, 10 pesos.
"""

# pregunto la edad del cliente
edadCliente = int(input("Ingrese su edad "))

# Concidiones
menorDe4 = 4
mayorEdad = 18

# Devolución
entradaGratis = 0
entradaMedia = 5
entradaPleno = 10

# Si el cliente tiene menos de 4 años
if edadCliente < menorDe4:
  print(f"El precio de la entrada es {entradaGratis} pesos")
# Si el cliente tiene entre 4 y 18
elif edadCliente > menorDe4 and edadCliente < mayorEdad:
  print(f"El precio de la entrada es {entradaMedia} pesos")
# Si no, el cliente es mayor de 18
else:
  print(f"El precio de la entrada es {entradaPleno} pesos")

"""### **Ejercicio 8 if**

Escriba un programa que pregunte primero si se quiere calcular el área de un triángulo o la de un círculo. Si se contesta que se quiere calcular el área de un triángulo (escribiendo T o t), el programa tiene que pedir entonces la base y la altura y escribir el área. Si se contesta que se quiere calcular el área de un círculo (escribiendo C o c), el programa tiene que pedir entonces el radio y escribir el área.

Se recuerda que el área de un triángulo es base por altura dividido por 2 y que el área de un círculo es Pi (aproximadamente 3,141592) por el radio al cuadrado.
"""

# Importo pi de numpy
import numpy as np

pi = np.pi

# Pregunto sobre qué calcular, area del triangulo o círculo
queCalculo = input("Ingrese T o t para calcular área de Triángulo \nIngrese C o c para calcular área de Círculo ").upper()
                                                                                            # Agrego .upper() para transformar a mayuscula
# Si se eligió calcular el área de un tringaulo
if queCalculo == "T":
  base = int(input("Ingrese el base "))
  altura = int(input("Ingrese el altura "))
  calcularArea = base * altura // 2
  print("El área del triangulo es ", calcularArea)
# Si se eligió calcular el área de un círculo
elif queCalculo == "C":
  radio = int(input("Ingrese el radio "))
  calcularArea = pi * (radio)**2 
  print("El área del círculo es ", calcularArea)

"""### **Ejercicio 1 while**

Mostrar por pantalla todos los números enteros entre 1 y 100, hacerlo usando un bucle while y tambien con un bucle for.
"""

# Iniciar una variable en cero
sumar = 0
# Preguntar mientras la variable no llegue a 100
while sumar < 100:
  # usar un acumulador de la variable
    sumar = sumar + 1
    print(sumar)
# Ciclo for
for sumar in range(sumar+1,101,1):
    print(sumar)

"""### **Ejercicio 2 while**

Escriba un programa que pregunte una y otra vez si desea continuar con el programa, siempre que se conteste exactamente sí (en minúsculas y con tilde).
"""

# Pregunto al usuario
pregunta = input("Responda sí , si desea continuar con el programa ")

while pregunta != "sí":
  # Inicio la pregunta hasta que sea respondida son sí
  pregunta = input("Responda sí , si desea continuar con el programa ")
print("Programa terminado")

"""### **Ejercicio 3 while**

Escriba un programa que pregunte una y otra vez si desea terminar el programa, salvo si se contesta exactamente SI (en mayúsculas y sin tilde).
"""

# Pregunto al usuario
pregunta = input("Responda SI , si desea terminar con el programa ")

while pregunta != "SI":
  # Inicio la pregunta hasta que sea respondida son sí
  pregunta = input("Responda SI  , si desea terminar con el programa ")
print("Programa terminado")

"""### **Ejercicio 4 while**

Escribir un programa que pida al usuario dos números enteros e imprima todos los números enteros entre ellos.
"""

# Pregunto al usuario dos numeros enteros
num1 = int(input("Ingrese un número entero "))
num2 = int(input("Ingrese un número entero "))

# 
while num1 < num2:
  num1 = num1 + 1
  print(num1)

"""### **Ejercicio 5 while**

Escriba un programa que solicite una contraseña (el texto de la contraseña no es importante) y la vuelva a solicitar hasta que las dos contraseñas coincidan.

Parte 2:
Al programa anterior agregarle una limitacion de 3 intentos como maximo.
"""

# Pregunto contraseña
password = input("Ingrese la contraseña ")
intentos = 0
passwordActual = 0
# Mientras la contraseña sea distinta a confimación e intentos menor a 3
while intentos != 3 and (password != passwordActual):
  # password != passwordActual and 
# and intentos > 3 :
  passwordActual = input("Confirme la contraseña ")
  intentos = intentos + 1
  ##################################################vv

"""### **Ejercicio 6 while**

Construir un programa que lea un número natural N y calcule la suma de los primeros N números pares.
"""

# ingreso numero natural
numNatural = int(input("Ingrese un numero positivo "))
suma = 0
i = 0
# Mientras i sea menor al numero ingresado
while i < numNatural:
  # input("Repetición") -- Comprobador que pasé el while y cantidad de repeticiones
  # Si el resto de i dividido 2 da 0, es par
  if (i % 2 == 0):
    # Agrego la variable suma
    suma
    # Sumo cada vez que haya numero par
    suma = suma + i
  # i se actualiza para que el while termine - Se podría usar el ciclo for 
  i = i + 1
# Imprimo la suma
print(suma)

"""### **Ejercicio 7 while**

Escribir un programa que recibe como entrada desde el usuario dos números enteros e informa por pantalla todos los números pares entre ellos.
"""

# El usuario ingresa dos números enteros
numEntero1 = int(input("Ingrese un número entero "))
numEntero2 = int(input("Ingrese otro número entero "))
suma = 0
# mientras el primer numero sea distinto al segundo número
while numEntero1 < numEntero2:
  # Si el resto de numEntero1 dividido 2 da 0, es par
  if ( numEntero1 % 2 == 0):
    # Imprimo los pares
    print(numEntero1)
  # numEntero1 se actualiza para que el while termine - Se podría usar el ciclo for 
  numEntero1 = numEntero1 + 1

"""### **Ejercicio 8 while**

Escribir un programa que pida un número entero y muestre por pantalla la cantidad de cifras de dicho número.
"""

# El usuario ingresa un número entero
numEntero1 = int(input("Ingrese un número entero "))
# Creo un acumulador de cifras
cifras = 0
# Mientras numero entero sea distinto a 0
while numEntero1 != 0:
  # Ingreso el acumulador
  cifras
  # Actualizo el valor de la variable dividida 10
  numEntero1 = numEntero1 // 10
  # Actualizo la variable cifras
  cifras = cifras + 1
# Imprimo el resultado
print(f"El número {numEntero1} tiene {cifras} cifras.")

"""### **Ejercicio 9 while**

Escriba un programa que simule una alcancia. El programa solicitará primero una cantidad, que será la cantidad de dinero que queremos ahorrar. A continuación, el programa solicitará una y otra vez las cantidades que se irán ahorrando, hasta que el total ahorrado iguale o supere al objetivo. El programa no comprobará que las cantidades sean positivas.

Parte 2:

Hacer que el programa verifique que las cantidades sean positivas. En caso de ser cero o valores negativos, que ingrese devuelte el valor.
"""

# El usuario ingresa un número
cantidadDeDinero = int(input("Ingrese una cantidad de dinero a ahorrar "))
# Ingreso un sumador
suma = 0
# Mientras la cantidad ingresada no sea igual o mayor a la suma
while suma <= cantidadDeDinero:
  # El usuario ingresa el dinero ahorrado
  dineroAhorrado = int(input("Ingresa el dinero ahorrado "))
  suma
  suma = dineroAhorrado + suma
  # print(suma) Comprobador de suma
print(f"Felicidades, el objetivo de ${cantidadDeDinero} ha sido alcanzado!")

# input1 = int(input())
#your code goes here
suma = 0
for i in range(100):
    suma
    suma = i + i
print(suma)

jxc = 94
auto = 12
todos = 62
izq = 27
libertad = 37

suma = jxc + auto + todos + izq + libertad

print(suma)

def porcentaje(partido):
    partido * 100 / suma
    print(partido)